
debug: true

# email sent to user instead of admin when live
live: false

http_listen: "127.0.0.1:23456"
json_pretty: true

token:
  header: "X-GO-POSTFIXADMIN-SECRET"
  secret: "cN9voqg6AYM0UhjX9pW2p1ZeiWGSNQw3"
  ips:
   - "127.0.0.1"
   - "56.45.56.45"


email_subject_prefix: "[go-postfixadmin] "
admin_email: "me@example.com"
from_email: "postmaster@example.com"
syslog_email: "postmaster@example.com"
test_email: "me@example.com"
noreply_email: "noreply@example.com"




imap_server: "mail.example.com"

default_domain: "example.com"
vacation_domain: "autoreply.example.com"


db:
  engine: mysql
  user: root
  password: mash
  database: mailserver_pfa
  debug: true
  table_prefix: ""
  table_names:
    admin: admin
    alias: alias
    alias_domain: alias_domain
    config: config
    domain: domain
    domain_admins: domain_admins
    fetchmail: fetchmail
    log: log
    mailbox: mailbox
    vacation: vacation
    vacation_notification: vacation_notification
    quota: quota
    quota2: quota2


smtp_server:
    server: mail.example.com
    port: 587
    login: wwwlogin@example.com
    password: secret999
    test_mode: true
